### ISSUE TITLE
需要用nodeclub搭建一个社区系统，还请解答几个疑问呢。

### ISSUE THREAD

**Issue by chaozaiai** [xiedacon/nodeclub-koa#9]
1、koa这个项目你还在维护吗？看todo list好几个还没做
2、nodeclub 我这边在windows环境下，配置不起来，能加好友交流下吗？

**Comment by xiedacon** [comment]
@chaozaiai 项目没有在维护了呢

windows 下跑不起来，是 docker 没起来吗？

qq: 1063462598

**Comment by chaozaiai** [comment]
@xiedacon  windows下面没有用docker。我想把nodeclub clone到win环境，配置好环境进行二次开发。
但是官方github上讲的都是linux环境。早上已经在centos环境配置好，并且运行起来了。
现在要在windows下二次开发，但是win下有没有make这些命令，项目根目录执行npm install 也会报错。这会儿把centos环境运行起来的项目代码，拉到win下，尝试一下。
实在不行，换下win下的node。
